package com.lihal.dynamo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "student")
public class Student {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String studentId;
	@DynamoDBAttribute
	private String studentName;
	@DynamoDBAttribute
	private String studentaddress;
	@DynamoDBAttribute
	private String studentEmailId;
	@DynamoDBAttribute
	private String studentContactNo;
	
	public String getStudentId() {
		return studentId;
	}
	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}
	public String getStudentName() {
		return studentName;
	}
	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}
	public String getStudentaddress() {
		return studentaddress;
	}
	public void setStudentaddress(String studentaddress) {
		this.studentaddress = studentaddress;
	}
	public String getStudentEmailId() {
		return studentEmailId;
	}
	public void setStudentEmailId(String studentEmailId) {
		this.studentEmailId = studentEmailId;
	}
	public String getStudentContactNo() {
		return studentContactNo;
	}
	public void setStudentContactNo(String studentContactNo) {
		this.studentContactNo = studentContactNo;
	}
	@Override
	public String toString() {
		return "Student [studentId=" + studentId + ", studentName=" + studentName + ", studentaddress=" + studentaddress
				+ ", studentEmailId=" + studentEmailId + ", studentContactNo=" + studentContactNo + "]";
	}
	
	
	
}
